### PR TITLE
Build wheels for Mac ARM

### PR DESCRIPTION
**Pull request by kylebarron**

### CODE REVIEW

**Comment by pypae** [comment]
Using this issue for a side-note, if anyone has the same issue.

When using [`hatch`](https://hatch.pypa.io/latest/) to install `pydelatin` on my M1 Mac, I got the following error (Not sure why, it works with system `pip`):

```
  error: subprocess-exited-with-error
  
  × Building wheel for pydelatin (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.0-arm64-cpython-312
      creating build/lib.macosx-11.0-arm64-cpython-312/pydelatin
      copying pydelatin/delatin.py -> build/lib.macosx-11.0-arm64-cpython-312/pydelatin
      copying pydelatin/util.py -> build/lib.macosx-11.0-arm64-cpython-312/pydelatin
      copying pydelatin/__init__.py -> build/lib.macosx-11.0-arm64-cpython-312/pydelatin
      copying pydelatin/py.typed -> build/lib.macosx-11.0-arm64-cpython-312/pydelatin
      running build_ext
      clang++ -fno-strict-overflow -DNDEBUG -g -O3 -Wall -arch arm64 -mmacosx-version-min=11.0 -Wno-nullability-completeness -Wno-expansion-to-defined -Wno-undef-prefix -fPIC -Werror=unguarded-availability-new "-I/Users/patrick/Library/Application Support/hatch/env/virtual/off-grid/iGlVZ8gk/off-grid/include" "-I/Users/patrick/Library/Application Support/hatch/env/virtual/.pythons/3.12/python/include/python3.12" -c flagcheck.cpp -o flagcheck.o -std=c++17
      building '_pydelatin' extension
      creating build/temp.macosx-11.0-arm64-cpython-312
      creating build/temp.macosx-11.0-arm64-cpython-312/src
      clang++ -fno-strict-overflow -DNDEBUG -g -O3 -Wall -arch arm64 -mmacosx-version-min=11.0 -Wno-nullability-completeness -Wno-expansion-to-defined -Wno-undef-prefix -fPIC -Werror=unguarded-availability-new -I/private/var/folders/_x/_vkzcmt13tq0mxvr3s_ptz300000gn/T/pip-build-env-t6vjmg1l/overlay/lib/python3.12/site-packages/pybind11/include "-I/Users/patrick/Library/Application Support/hatch/env/virtual/off-grid/iGlVZ8gk/off-grid/include" "-I/Users/patrick/Library/Application Support/hatch/env/virtual/.pythons/3.12/python/include/python3.12" -c src/base.cpp -o build/temp.macosx-11.0-arm64-cpython-312/src/base.o -std=c++17 -mmacosx-version-min=10.14 -fvisibility=hidden -g0
      In file included from src/base.cpp:1:
      src/base.h:3:10: fatal error: 'glm/glm.hpp' file not found
      #include <glm/glm.hpp>
               ^~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pydelatin
ERROR: Could not build wheels for pydelatin, which is required to install pyproject.toml-based projects
```

Installing `glm` and adding it to the `PATH` worked fine:

```
brew install glm 
export CPLUS_INCLUDE_PATH=$(brew --prefix glm)/include:$CPLUS_INCLUDE_PATH
```

**Comment by kylebarron** [comment]
Well it's not clear why it's building from source. A PR to update the wheel builds would be welcome. pydelatin probably doesn't work with numpy v2

**Comment by pypae** [comment]
> Well it's not clear why it's building from source. A PR to update the wheel builds would be welcome. pydelatin probably doesn't work with numpy v2

- I worked with numpy 2.1.0 and creating a mesh worked fine!
- Might simply be the macOS version? I have 13, while the [build workflow uses 11](https://github.com/kylebarron/pydelatin/blob/6af82ca60092cdd5c53c34e3e084015af393372a/.github/workflows/build-wheels.yml#L15C29-L15C37). I'll have a look tomorrow. 

_Thanks by the way for the awesome project!_

**Comment by kylebarron** [comment]
yeah you might have to update the macos version in the workflow
